FROM mojotech/debian:latest

RUN apt-get install -y --no-install-recommends \
      build-essential \
      git \
      lsof \
      nodejs-legacy \
      npm/local \
      python

ENV NODE_PATH /usr/local/lib/node_modules
