FROM mojotech/debian:latest
MAINTAINER mojotech <ops+docker@mojotech.com>

RUN apt-get install -y --no-install-recommends -t local \
      nodejs-legacy \
      npm \
      python

ENV NODE_PATH /usr/local/lib/node_modules
