FROM mojotech/debian:latest
MAINTAINER mojotech <ops+docker@mojotech.com>

RUN apt-get install -y --no-install-recommends -t local \
      python \
      python-dev \
      python-pip \
      python-virtualenv
