FROM mojotech/debian:latest
MAINTAINER mojotech <ops+docker@mojotech.com>

RUN apt-get install -y --no-install-recommends -t local \
      oracle-java7-jdk

RUN apt-get install -y --no-install-recommends -t local \
      gradle
